### ISSUE TITLE
Local file inclusion in SOY CMS

### ISSUE THREAD

**Issue by stypr** [inunosinsi/soycms#18]
I thought I reported it. Sorry!

---

## Title
Local File Inclusion in SOY CMS

## Summary
Severity: Low
SoyCMS 3.0.2 and earlier is affected by Local File Inclusion (LFI). The allows remote attackers to execute any PHP when user is capable of uploading any arbitrary script.

Attack vector is: Admin must be logged in, Invalid PHP file must be uploaded.
Components are: Soy Inquiry Form
Tested SoyCMS Version : 3.0.2 (latest)
Affected SoyCMS Version : ~3.0.2

Found by @stypr from Vulnerability Research Team in [Flatt Security Inc.](https://flatt.tech/)

##  Cause

https://github.com/inunosinsi/soycms/blob/41931745c680cb1cfc3d5e18d19c7e765a712bc1/cms/app/webapp/inquiry/admin.php#L73-L76
This code is not filtered anywhere, which needs to be fixed.

## Remediation

Change to the following code.
```php

if(isset($_GET["bat"])){
     $bat = str_replace(Array("..", "/", "\\"), "_", $_GET['bat']);
     $filename = dirname(__FILE__) . "/src/bat/" . $bat . ".php";
     if(file_exists($filename)){
          include($filename);
          exit;
     }
```

**Comment by inunosinsi** [comment]
Tanky you.
The code is not used in the current version, so it has been abolished.

**Comment by stypr** [comment]
Confirmed. Thank you! Closing.
