### ISSUE TITLE
There is one vulnerability that can getshell(Execute arbitrary php code)

### ISSUE THREAD

**Issue by Ryan0lb** [inunosinsi/soycms#5]
There is one vulnerability that can getshell(Execute arbitrary php code)
Affected software:Soycms v3.0.2
Type of vulnerability:Execute arbitrary php code(can getshell)
Discovered by: Yu Yang
Affected URL:http://127.0.0.1/soycms/admin/index.php/Site/EditController/1

First,we can install the cms successlly,and we can create a new website
![image](https://user-images.githubusercontent.com/15329046/55385120-fb205e00-555e-11e9-8ee0-14f8b33f2c7f.png)
we can insert arbitrary php code in the http://xxx.xxx.xxx/'New directory'/index.php 
![image](https://user-images.githubusercontent.com/15329046/55385263-49356180-555f-11e9-9043-99b2e5cc133f.png)
So.Finally,we can insert the malicious code,and getshell
![image](https://user-images.githubusercontent.com/15329046/55385406-a8937180-555f-11e9-8552-f0ea2f9eec6c.png)

**Comment by inunosinsi** [comment]
Thank you for contacting me.
This page was created on the assumption that SSH is made editable on its own.
I will consider the action by enriching the explanation of the page.

**Comment by stypr** [comment]
This was not fixed properly.
I've added PRs to address this issue.
